name: Build and Publish Python Package

on:
  release:
    types: [created]

jobs:
  
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Use the latest version of Python 3.x here

    - name: Update version.py with release tag
      env:
        RELEASE_TAG: ${{ github.event.release.tag_name }}
      run: |
        python .github/scripts/python/update_version.py --version $RELEASE_TAG --path "src/version.txt"

  build-wheels:
    name: Build wheels on ${{ matrix.python-version }} for ${{ matrix.manylinux-version }}
    runs-on: ubuntu-latest
    # Only run this job after the bump-version job has completed
    needs: bump-version
    if: github.event_name == 'release' && github.event.action == 'created'
    strategy:
      matrix:
        python-version: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310, cp311-cp311, cp312-cp312]
        manylinux-version: [manylinux2014]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Pull Docker image
      run: docker pull quay.io/pypa/${{ matrix.manylinux-version }}_x86_64

    - name: Build and repair wheels
      run: |
        docker run --rm -v ${{ github.workspace }}:/io quay.io/pypa/${{ matrix.manylinux-version }}_x86_64 /bin/bash -c "
          cd /io &&
          /opt/python/${{ matrix.python-version }}/bin/python setup.py bdist_wheel -d /io/wheelhouse &&
          auditwheel repair /io/wheelhouse/*.whl -w /io/wheelhouse/repaired
        "

    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: wheelhouse/repaired/*.whl
  
  publish-to-pypi:
    name: Upload release to PyPI
    needs: build-wheels
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Use the latest version of Python 3.x here

    - name: Update version.py with release tag
      env:
        RELEASE_TAG: ${{ github.event.release.tag_name }}
      run: |
        python .github/scripts/python/update_version.py --version $RELEASE_TAG --path "src/version.txt"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Download built wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels

    - name: Build package
      run: |
        python setup.py sdist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1